# Generated by Django 3.0.5 on 2020-04-15 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=1)),
                ('insurance_amount', models.IntegerField(default=1)),
                ('destination', models.CharField(default='', max_length=15)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('file', models.FileField(default='default.jpg', upload_to='')),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
